<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Estoque.Application.Services</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Entities\Estoque.Domain.Entities.csproj" />
    <ProjectReference Include="..\..\Domain\Interfaces\Estoque.Domain.Interfaces.csproj" />
    <ProjectReference Include="..\DTOs\Estoque.Application.DTOs.csproj" />
  </ItemGroup>
</Project>
