apiVersion: v1
kind: Service
metadata:
  name: techchallenger-api
  labels:
    app: techchallenger-api
spec:
  type: NodePort
  selector:
    app: techchallenger-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
