apiVersion: v1
kind: ConfigMap
metadata:
  name: techchallenger-api-config
  labels:
    app: techchallenger-api
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "TechChallenger"
  Jwt__Audience: "TechChallenger"
  Jwt__ExpirationMinutes: "60"
  Email__Habilitado: "true"
  Email__Port: "587"
  Email__UseSsl: "true"
  Email__FromAddress: "naoresponda@techchallenger.com"
  Email__FromName: "TechChallenger Oficina"
  Email__TentativasMaximas: "3"
  Email__DelayInicialSegundos: "2"
