apiVersion: v1
kind: Service
metadata:
  name: techchallenger-api
  labels:
    app: techchallenger-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: techchallenger-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
