<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Estoque.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Estoque.Domain.csproj" />
    <ProjectReference Include="..\..\Compartilhado\Infrastructure\Compartilhado.Infrastructure.csproj" />
  </ItemGroup>
</Project>
