<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Atendimento.Presentation.Controllers</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\Services\Atendimento.Application.Services.csproj" />
    <ProjectReference Include="..\..\Application\DTOs\Atendimento.Application.DTOs.csproj" />
  </ItemGroup>
</Project>
