<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Operacao.Domain.Interfaces</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Entities\Operacao.Domain.Entities.csproj" />
  </ItemGroup>
</Project>
