<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Compartilhado.Domain.Entities</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ValueObjects\Compartilhado.Domain.ValueObjects.csproj" />
  </ItemGroup>
</Project>
